#### Dataset Summary ####
'MOVIES DATASET FOR FEATURE EXTRACTION, PREDICTION' from Kaggle contains various attributes of movies aimed at facilitating feature extraction and prediction tasks. The dataset includes the following columns:

- Movies: The title of the movie.
- Year: The release year of the movie.
- Genre: The genre(s) of the movie.
- Rating: The IMDb rating of the movie.
- One-Line: A one-line description or tagline of the movie.
- Stars: A mixed column containing both directors and stars of the movie.
- Votes: The number of votes the movie received on IMDb.
- RunTime: The runtime of the movie in minutes.
- Gross: The gross revenue of the movie.

#### Leaning Objectives ####
- Key: Clean the dataset with the gathered business question in mind. Ensure that it will answer the questions.
- Support: Any guidance refer to ChatGPT for detailed explanations
1. Remove duplicated rows
2. Remove unnecessary characters / whitespace / column(s) / NAs
3. Standardise with consistent formatting
4. Fill in NaN / None values with empty string for a cleaner look
5. Split a column to several columns for categorization

#### Business Questions ####
1. What are the most common genres in the dataset, and how are they distributed?
2. Which movies have the highest and lowest ratings, and what are their common attributes (e.g., genre, runtime, stars)?
3. Which movies have the highest and lowest votes, and what are their common attributes (e.g., genre, runtime, stars)?
4. Who are the most influential directors and stars in terms of movie ratings and gross revenue?

In [550]:
import pandas as pd
import numpy as np

In [296]:
df = pd.read_csv(r"C:\Users\USER\Jupyter Projects\Raw Datasets\Movies_Datasets_Pandas_DataCleaning.csv")
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [5]:
# Shows us the top 20 rows of the Movie dataset

In [297]:
df.head(20)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN
10,Gunpowder Milkshake,(2021),"\nAction, Adventure, Thriller",6.0,\nThree generations of women fight back agains...,\n Director:\nNavot Papushado\n| \n Star...,"17,989",114.0,NaN
11,Lucifer,(2016–2021),"\nCrime, Drama, Fantasy",8.1,\nLucifer Morningstar has decided he's had eno...,"\n \n Stars:\nTom Ellis, \nLesle...","264,222",42.0,NaN
12,Fear Street: 1994,(2021),"\nDrama, Horror, Mystery",6.2,\nA circle of teenage friends accidentally enc...,\n Director:\nLeigh Janiak\n| \n Stars:\...,"50,148",107.0,NaN
13,Sex/Life,(2021– ),"\nComedy, Drama, Romance",5.4,\nA suburban mother of two takes a fantasy-cha...,"\n \n Stars:\nSarah Shahi, \nMik...","12,172",NaN,NaN
14,American Horror Story,(2011– ),"\nDrama, Horror, Thriller",8.0,\nAn anthology series centering on different c...,"\n \n Stars:\nLady Gaga, \nKathy...","286,488",60.0,NaN
15,Grey's Anatomy,(2005– ),"\nDrama, Romance",7.5,\nA drama centered on the personal and profess...,"\n \n Stars:\nEllen Pompeo, \nCh...","266,258",41.0,NaN
16,Breaking Bad,(2008–2013),"\nCrime, Drama, Thriller",9.4,\nA high school chemistry teacher diagnosed wi...,"\n \n Stars:\nBryan Cranston, \n...","1,552,311",49.0,NaN
17,The Good Doctor,(2017– ),\nDrama,8.1,"\nShaun Murphy, a young surgeon with autism an...","\n \n Stars:\nFreddie Highmore, ...","70,871",41.0,NaN
18,Atypical,(2017–2021),"\nComedy, Drama",8.3,"\nSam, an 18-year-old on the autism spectrum, ...",\n \n Stars:\nJennifer Jason Lei...,"71,544",30.0,NaN
19,Stranger Things,(2016– ),"\nDrama, Fantasy, Horror",8.7,"\nWhen a young boy disappears, his mother, a p...",\n \n Stars:\nMillie Bobby Brown...,"885,856",51.0,NaN

In [8]:
# Gives us the last 20 rows of the Movie Dataset

In [7]:
df.tail(20)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
9979,Never Have I Ever,(2020– ),\nComedy,8.8,\nAs Paxton's mixed messages have Devi questio...,\n Director:\nLang Fisher\n| \n Stars:\n...,433,NaN,NaN
9980,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9981,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9982,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9983,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n Director:\nPaul Wilmshurst\n| \n Star...,NaN,NaN,NaN
9984,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n Director:\nPaul Wilmshurst\n| \n Star...,NaN,NaN,NaN
9985,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n Director:\nPaul Wilmshurst\n| \n Star...,NaN,NaN,NaN
9986,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9987,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n Director:\nAnthony Philipson\n,NaN,NaN,NaN
9988,The Last Kingdom,(2015– ),"\nAction, Drama, History",NaN,\nAdd a Plot\n,\n Director:\nAnthony Philipson\n,NaN,NaN,NaN
9989,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9990,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9991,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9992,1899,(2022– ),"\nDrama, History, Horror",NaN,\nAdd a Plot\n,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9993,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### **Check for Duplicates** ####
1. First, check how many total rows before dropping the duplicated rows
2. Count how many in total duplicated rows
3. Drop the duplicates using '.drop_duplicates()'
4. Finally, check if after dropping the duplicates - it's giving us the correct total number of unique rows.

In [10]:
total_rows = len(df)
total_rows

9999

In [11]:
# Show where the duplicates are

In [16]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9994     True
9995    False
9996    False
9997    False
9998    False
Length: 9999, dtype: bool

In [17]:
# Tells us how many duplicates there are

In [15]:
df.duplicated().sum()

431

In [299]:
df = df.drop_duplicates()
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [25]:
# Reconfirming that the total number of duplicates (431) computes correctly with the remaining rows (9568)
# 9999 rows - 431 duplicates = 9568 unique rows

In [22]:
total_rows_drop_duplicates = len(df)
total_rows_drop_duplicates

9568

#### **Removing The Unneccesary Column(s)** ####
1. Based on the requirements or questions, 'One-Line' column is not needed, hence, we will be removing it
2. Remove column using '.drop(columns = '<COLUMN NAME>')

In [300]:
df = df.drop(columns="ONE-LINE")
df

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9993,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### **Clean & Standardize Columns** ####


#### YEAR Column ####
1. Removing the hypens and brackets to standardize the formatting

#### Challenge ####
1. After removing the brackets, I can't seem to strip the hyphen from the standalone year (eg. 2021-).

#### Solution ####
1. Consulted ChatGPT to learn how to remove the hyphen from standalone year by using '.replace' and regex pattern.

#### Learned #####
1. Using '.replace' it will replace any hyphen value with an empty string ' ' by using **r'–\s*$'** which is a regex pattern
2. Let's break down this regex pattern from ChatGPT:
- **'–'** : Matches the hyphen character (you can also use the standard hyphen '-' if it matches the specific hyphen used in your data).
  
- \s*: Matches zero or more whitespace characters (spaces, tabs, etc.).
  
- **$**: Asserts the position at the end of the string.

Basically, saying that hyphen - followed by zero or more spaces at the end of the string (eg. '2021-' , '2013-') - is removed. Hence, it left '2010-2022' unchanged.

In [301]:
df["YEAR"] = df["YEAR"].str.strip('()')
df.head(30)

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,2020–,"\nAction, Crime, Drama",7.6,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,2021,"\nDrama, Romance",6.8,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,2006–2013,"\nCrime, Drama, Mystery",8.6,"\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,2020–,\nComedy,7.9,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,2019–,"\nDrama, Romance",7.4,\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN
10,Gunpowder Milkshake,2021,"\nAction, Adventure, Thriller",6.0,\n Director:\nNavot Papushado\n| \n Star...,"17,989",114.0,NaN
11,Lucifer,2016–2021,"\nCrime, Drama, Fantasy",8.1,"\n \n Stars:\nTom Ellis, \nLesle...","264,222",42.0,NaN
12,Fear Street: 1994,2021,"\nDrama, Horror, Mystery",6.2,\n Director:\nLeigh Janiak\n| \n Stars:\...,"50,148",107.0,NaN
13,Sex/Life,2021–,"\nComedy, Drama, Romance",5.4,"\n \n Stars:\nSarah Shahi, \nMik...","12,172",NaN,NaN
14,American Horror Story,2011–,"\nDrama, Horror, Thriller",8.0,"\n \n Stars:\nLady Gaga, \nKathy...","286,488",60.0,NaN
15,Grey's Anatomy,2005–,"\nDrama, Romance",7.5,"\n \n Stars:\nEllen Pompeo, \nCh...","266,258",41.0,NaN
16,Breaking Bad,2008–2013,"\nCrime, Drama, Thriller",9.4,"\n \n Stars:\nBryan Cranston, \n...","1,552,311",49.0,NaN
17,The Good Doctor,2017–,\nDrama,8.1,"\n \n Stars:\nFreddie Highmore, ...","70,871",41.0,NaN
18,Atypical,2017–2021,"\nComedy, Drama",8.3,\n \n Stars:\nJennifer Jason Lei...,"71,544",30.0,NaN
19,Stranger Things,2016–,"\nDrama, Fantasy, Horror",8.7,\n \n Stars:\nMillie Bobby Brown...,"885,856",51.0,NaN
20,Fear Street: 1978,2021,"\nDrama, Horror, Mystery",6.8,\n Director:\nLeigh Janiak\n| \n Stars:\...,"36,634",109.0,NaN
21,Friends,1994–2004,"\nComedy, Romance",8.9,"\n \n Stars:\nJennifer Aniston, ...","880,918",22.0,NaN
22,The Flash,2014–,"\nAction, Adventure, Drama",7.6,"\n \n Stars:\nGrant Gustin, \nCa...","320,264",43.0,NaN
23,Peaky Blinders,2013–,"\nCrime, Drama",8.8,"\n \n Stars:\nCillian Murphy, \n...","393,414",60.0,NaN
24,He-Man and the Masters of the Universe,2021–,"\nAnimation, Action, Adventure",NaN,\n,NaN,NaN,NaN
25,Chernobyl,2021,"\nDrama, History, Romance",5.0,\n Director:\nDanila Kozlovskiy\n| \n St...,"4,681",136.0,NaN
26,Vikings,2013–2020,"\nAction, Adventure, Drama",8.5,"\n \n Stars:\nKatheryn Winnick, ...","459,913",44.0,NaN
27,Better Call Saul,2015–,"\nCrime, Drama",8.8,"\n \n Stars:\nBob Odenkirk, \nRh...","347,857",46.0,NaN
28,Supernatural,2005–2020,"\nDrama, Fantasy, Horror",8.4,"\n \n Stars:\nJared Padalecki, \...","404,273",44.0,NaN
29,The Blacklist,2013–,"\nCrime, Drama, Mystery",8.0,"\n \n Stars:\nJames Spader, \nMe...","213,522",43.0,NaN

In [43]:
# Remove the hyphen (-) for standalone year (eg. 2022) 
# For year ranges, it will remain unchanged (eg. 2010-2022)

In [302]:
df["YEAR"] = df["YEAR"].str.replace(r'–\s*$', '', regex=True)
df

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,"\nAnimation, Action, Adventure",5.0,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,"\nAnimation, Adventure, Comedy",9.2,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9993,Totenfrau,2022,"\nDrama, Thriller",NaN,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9995,Arcane,2021,"\nAnimation, Action, Adventure",NaN,\n,NaN,NaN,NaN
9996,Heart of Invictus,2022,"\nDocumentary, Sport",NaN,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### GENRE Column ####
1. Removing the slashes '\' and 'n' which is called newline character from the string

In [303]:
df["GENRE"] = df["GENRE"].str.strip('\n')
df.tail(50)

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross
9909,Pretty Smart,NaN,Comedy,NaN,"\n \n Stars:\nCinthya Carmona, \...",NaN,NaN,NaN
9910,Pretty Smart,NaN,Comedy,NaN,\n Director:\nJody Margolin Hahn\n| \n S...,NaN,NaN,NaN
9914,Castlevania,2017–2021,"Animation, Action, Adventure",8.3,\n Director:\nSam Deats\n| \n Stars:\nRi...,980,24.0,NaN
9915,Girl From Nowhere,2018,"Crime, Drama, Fantasy",7.8,\n Director:\nPairach Khumwan\n| \n Star...,183,NaN,NaN
9916,Girl From Nowhere,2018,"Crime, Drama, Fantasy",6.5,\n Director:\nKomgrit Triwimol\n| \n Sta...,145,NaN,NaN
9917,Girl From Nowhere,2018,"Crime, Drama, Fantasy",8.2,\n Director:\nPairach Khumwan\n| \n Star...,147,NaN,NaN
9918,Girl From Nowhere,2018,"Crime, Drama, Fantasy",8.3,\n Director:\nSitisiri Mongkolsiri\n| \n ...,144,NaN,NaN
9919,Girl From Nowhere,2018,"Crime, Drama, Fantasy",7.5,\n Director:\nKomgrit Triwimol\n| \n Sta...,140,NaN,NaN
9920,Girl From Nowhere,2018,"Crime, Drama, Fantasy",8.5,"\n Directors:\nPaween Purijitpanya, \nSuraw...",158,NaN,NaN
9921,Girl From Nowhere,2018,"Crime, Drama, Fantasy",8.0,\n Director:\nJatuphong Rungrueangdechaphat...,110,NaN,NaN
9922,Girl From Nowhere,2018,"Crime, Drama, Fantasy",8.1,\n Director:\nKomgrit Triwimol\n| \n Sta...,112,NaN,NaN
9923,Ginny & Georgia,2021,"Comedy, Drama",NaN,\n Director:\nAnya Adams\n| \n Stars:\nB...,NaN,NaN,NaN
9933,Dota: Dragon's Blood,2021,"Animation, Action, Adventure",NaN,\n,NaN,NaN,NaN
9934,Master of None,2015,"Comedy, Drama",5.8,\n Director:\nAziz Ansari\n| \n Stars:\n...,"1,173",55.0,NaN
9935,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9936,Élite,2018,"Crime, Drama, Thriller",NaN,"\n \n Stars:\nItzan Escamilla, \...",NaN,NaN,NaN
9937,"Love, Death & Robots",2019,"Animation, Short, Comedy",6.6,\n Director:\nAlex Beaty\n| \n Stars:\nM...,"5,659",13.0,NaN
9938,Master of None,2015,"Comedy, Drama",5.7,\n Director:\nAziz Ansari\n| \n Stars:\n...,658,31.0,NaN
9939,La casa de papel,2017–2021,"Action, Crime, Mystery",NaN,\n,NaN,NaN,NaN
9948,Élite,2018,"Crime, Drama, Thriller",NaN,"\n \n Stars:\nGeorgina Amorós, \...",NaN,NaN,NaN
9950,"Love, Death & Robots",2019,"Animation, Short, Comedy",6.1,\n Director:\nRobert Valley\n| \n Stars:...,"6,739",13.0,NaN
9951,"Love, Death & Robots",2019,"Animation, Short, Comedy",7.0,\n Director:\nSimon Otto\n| \n Stars:\nJ...,"6,039",11.0,NaN
9952,"Love, Death & Robots",2019,"Animation, Short, Comedy",6.5,\n Director:\nMeat Dept\n| \n Stars:\nNa...,"7,098",12.0,NaN
9953,"Love, Death & Robots",2019,"Animation, Short, Comedy",7.4,\n Director:\nElliot Dear\n| \n Stars:\n...,"6,163",7.0,NaN
9954,"Love, Death & Robots",2019,"Animation, Short, Comedy",7.0,\n Director:\nTim Miller\n| \n Stars:\nS...,"5,868",13.0,NaN
9955,"Love, Death & Robots",2019,"Animation, Short, Comedy",7.9,"\n Directors:\nDominique Boidin, \nLéon Bér...","6,873",18.0,NaN
9956,Sexify,2021,"Comedy, Drama",6.9,\n Director:\nPiotr Domalewski\n| \n Sta...,138,50.0,NaN
9957,Sexify,2021,"Comedy, Drama",6.9,\n Director:\nPiotr Domalewski\n| \n Sta...,126,40.0,NaN
9958,Sexify,2021,"Comedy, Drama",6.9,\n Director:\nPiotr Domalewski\n| \n Sta...,116,49.0,NaN
9959,Sexify,2021,"Comedy, Drama",6.8,\n Director:\nKalina Alabrudzinska\n| \n ...,108,38.0,NaN
9960,Sexify,2021,"Comedy, Drama",7.1,\n Director:\nKalina Alabrudzinska\n| \n ...,103,37.0,NaN
9961,Sexify,2021,"Comedy, Drama",6.9,\n Director:\nKalina Alabrudzinska\n| \n ...,96,40.0,NaN
9962,Sexify,2021,"Comedy, Drama",7.1,\n Director:\nKalina Alabrudzinska\n| \n ...,100,47.0,NaN
9963,Castlevania,2017–2021,"Animation, Action, Adventure",8.2,\n Director:\nSam Deats\n| \n Stars:\nRi...,911,24.0,NaN
9964,AlRawabi School for Girls,2021,Drama,NaN,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
9965,AlRawabi School for Girls,2021,Drama,NaN,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
9966,AlRawabi School for Girls,2021,Drama,NaN,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
9967,AlRawabi School for Girls,2021,Drama,NaN,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
9975,Ultraman,2019,"Animation, Action, Adventure",NaN,"\n \n Stars:\nRyohei Kimura, \nJ...",NaN,NaN,NaN
9976,The Talk,2010,Talk-Show,NaN,"\n \n Stars:\nSheryl Underwood, ...",NaN,38.0,NaN
9979,Never Have I Ever,2020,Comedy,8.8,\n Director:\nLang Fisher\n| \n Stars:\n...,433,NaN,NaN
9980,1899,2022,"Drama, History, Horror",NaN,\n Director:\nBaran bo Odar\n,NaN,NaN,NaN
9983,The Last Kingdom,2015,"Action, Drama, History",NaN,\n Director:\nPaul Wilmshurst\n| \n Star...,NaN,NaN,NaN
9986,The Last Kingdom,2015,"Action, Drama, History",NaN,\n,NaN,NaN,NaN
9987,The Last Kingdom,2015,"Action, Drama, History",NaN,\n Director:\nAnthony Philipson\n,NaN,NaN,NaN
9993,Totenfrau,2022,"Drama, Thriller",NaN,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9995,Arcane,2021,"Animation, Action, Adventure",NaN,\n,NaN,NaN,NaN
9996,Heart of Invictus,2022,"Documentary, Sport",NaN,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### STARS Column ####
1. Create 2 new columns for 'Director' and 'Stars'
2. Clean up and standardise each column and removing whitespaces
3. Handle the missing values 

#### Challenges ####
1. I had to backtrack because I realised that after splitting the 'STARS' column into 2 columns. The some of the rows are not showing the proper string - it's showing NaN instead. Hence, I had to redo the splitting of columns.
--> After doing some research, the NaN shows up when there is no delimiter '|' in that specific row. Hence, giving us NaN.

In [98]:
# Delete the 'Director' and 'Star(s)' columns to redo the entire process again due to rows only showing NaN.

# Use .drop(["Director","Star(s)"], axis=1) delete couple rows at the same time
# 'axis=1' is used if you want to delete COLUMNS
# 'axis=0' is used if you want to delete ROWS/though rows are typically identified by index values rather than names.

# ALTERNATIVES: 
# .drop(columns=['col1', 'col2']) -> Suitable for MULTIPLE column deletion
# del df['col'] -> More suitable for SINGLE column deletion
# df.pop('col') -> More suitable for SINGLE column deletion

In [ ]:
df = df.drop(columns=["Director","Stars"])

In [164]:
# Remove whitespace in the 'Stars' column

In [305]:
df["STARS"] = df["STARS"].str.strip()
df

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,Director:\nPeter Thorwarth\n| \n Stars:\nPe...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,"Stars:\nChris Wood, \nSarah Michelle Gellar, \...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",8.2,"Stars:\nAndrew Lincoln, \nNorman Reedus, \nMel...","885,805",44.0,NaN
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,"Stars:\nJustin Roiland, \nChris Parnell, \nSpe...","414,849",23.0,NaN
4,Army of Thieves,2021,"Action, Crime, Horror",NaN,Director:\nMatthias Schweighöfer\n| \n Star...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9993,Totenfrau,2022,"Drama, Thriller",NaN,Director:\nNicolai Rohde\n| \n Stars:\nFeli...,NaN,NaN,NaN
9995,Arcane,2021,"Animation, Action, Adventure",NaN,,NaN,NaN,NaN
9996,Heart of Invictus,2022,"Documentary, Sport",NaN,Director:\nOrlando von Einsiedel\n| \n Star...,NaN,NaN,NaN
9997,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,Director:\nJovanka Vuckovic\n| \n Stars:\nM...,NaN,NaN,NaN
9998,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,Director:\nJovanka Vuckovic\n| \n Stars:\nM...,NaN,NaN,NaN

In [166]:
# Split the Stars column into 2 more columns 'Director' & 'Stars'

In [306]:
df[['Director', 'Stars']] = df['STARS'].str.split('|', expand=True)

In [226]:
df

,MOVIES,YEAR,GENRE,RATING,STARS,VOTES,RunTime,Gross,Director,Stars
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,Director:\nPeter Thorwarth\n| \n Stars:\nPe...,"21,062",121.0,NaN,Director:\nPeter Thorwarth\n,"\n Stars:\nPeri Baumeister, \nCarl Anton K..."
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,"Stars:\nChris Wood, \nSarah Michelle Gellar, \...","17,870",25.0,NaN,"Stars:\nChris Wood, \nSarah Michelle Gellar, \...",None
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",8.2,"Stars:\nAndrew Lincoln, \nNorman Reedus, \nMel...","885,805",44.0,NaN,"Stars:\nAndrew Lincoln, \nNorman Reedus, \nMel...",None
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,"Stars:\nJustin Roiland, \nChris Parnell, \nSpe...","414,849",23.0,NaN,"Stars:\nJustin Roiland, \nChris Parnell, \nSpe...",None
4,Army of Thieves,2021,"Action, Crime, Horror",NaN,Director:\nMatthias Schweighöfer\n| \n Star...,NaN,NaN,NaN,Director:\nMatthias Schweighöfer\n,"\n Stars:\nMatthias Schweighöfer, \nNathal..."
...,...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,2022,"Drama, Thriller",NaN,Director:\nNicolai Rohde\n| \n Stars:\nFeli...,NaN,NaN,NaN,Director:\nNicolai Rohde\n,"\n Stars:\nFelix Klare, \nRomina Küper, \n..."
9995,Arcane,2021,"Animation, Action, Adventure",NaN,,NaN,NaN,NaN,,None
9996,Heart of Invictus,2022,"Documentary, Sport",NaN,Director:\nOrlando von Einsiedel\n| \n Star...,NaN,NaN,NaN,Director:\nOrlando von Einsiedel\n,\n Star:\nPrince Harry
9997,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,Director:\nJovanka Vuckovic\n| \n Stars:\nM...,NaN,NaN,NaN,Director:\nJovanka Vuckovic\n,"\n Stars:\nMorgan Taylor Campbell, \nIñaki..."
9998,The Imperfects,2021,"Adventure, Drama, Fantasy",NaN,Director:\nJovanka Vuckovic\n| \n Stars:\nM...,NaN,NaN,NaN,Director:\nJovanka Vuckovic\n,"\n Stars:\nMorgan Taylor Campbell, \nJenni..."

In [ ]:
# Replacing the 'Directors:\n' with empty string and then removing white spaces

In [307]:
df['Director'] = df['Director'].str.replace('Director:\n','').str.replace('Directors:\n','').str.strip()

In [ ]:
# Replacing the 'Star:\n' with empty string and then removing whitespaces

In [308]:
df['Stars'] = df['Stars'].str.strip().str.replace('Stars:\n','').str.replace('Star:\n','')

In [184]:
# Move those strings that has 'Stars' under Stars column
# This list shows us which rows that are TRUE that contains 'Stars'

In [309]:
df['Director'].str.contains('Stars', na=False)

0       False
1        True
2        True
3        True
4       False
        ...
9993    False
9995    False
9996    False
9997    False
9998    False
Name: Director, Length: 9568, dtype: bool

In [186]:
# Creating a 'mask' boolean mask identifying rows in the 'Director' column that contains 'Stars'
# Identify rows in the 'Director' column that contain 'Stars'

In [310]:
mask = df['Director'].str.contains('Stars', na=False)

In [188]:
# Move the identified rows from 'Director' to 'Stars'
# Assigns the values from the 'Director' column to the 'Stars' column for the identified rows.

In [311]:
df.loc[mask, 'Stars'] = df.loc[mask, 'Director']

In [190]:
# Set the 'Director' column for these rows to an empty string or NaN

In [312]:
df.loc[mask, 'Director'] = ''

In [247]:
# Removing whitespace and replacing strings with an empty string

In [313]:
df['Stars'] = df['Stars'].str.strip()

In [314]:
df['Stars'] = df['Stars'].str.replace('Stars:\n','').str.replace('Star:\n','')

In [253]:
# Replacing all the '\n' in the middle of the string in the Star column

In [315]:
df['Stars'] = df['Stars'].str.replace('\n', ' ', regex=False)

In [ ]:
# Replacing all the '\n' in the middle of the string in the Director column

In [316]:
df['Director'] = df['Director'].str.replace('\n', ' ', regex=False)

In [268]:
# Fill in empty string to all the NaN / None

In [317]:
df = df.fillna('')

In [269]:
# Drop the unnecessary column such as 'STARS'

In [318]:
df = df.drop(columns='STARS')

In [274]:
# Reset the index column to make it consecutive

In [319]:
df = df.reset_index(drop=True)

In [583]:
df["GENRE"] = df["GENRE"].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

In [584]:
df.head(10)

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,"21,062",121.0,,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander ..."
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,"17,870",25.0,,,"Chris Wood, Sarah Michelle Gellar, Lena Head..."
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",8.2,"885,805",44.0,,,"Andrew Lincoln, Norman Reedus, Melissa McBri..."
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,"414,849",23.0,,,"Justin Roiland, Chris Parnell, Spencer Gramm..."
4,Army of Thieves,2021,"Action, Crime, Horror",,,,,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ru..."
5,Outer Banks,2020,"Action, Crime, Drama",7.6,"25,858",50.0,,,"Chase Stokes, Madelyn Cline, Madison Bailey,..."
6,The Last Letter from Your Lover,2021,"Drama, Romance",6.8,"5,283",110.0,,Augustine Frizzell,"Shailene Woodley, Joe Alwyn, Wendy Nottingha..."
7,Dexter,2006–2013,"Crime, Drama, Mystery",8.6,"665,387",53.0,,,"Michael C. Hall, Jennifer Carpenter, David Z..."
8,Never Have I Ever,2020,Comedy,7.9,"34,530",30.0,,,"Maitreyi Ramakrishnan, Poorna Jagannathan, D..."
9,Virgin River,2019,"Drama, Romance",7.4,"27,279",44.0,,,"Alexandra Breckenridge, Martin Henderson, Co..."

#### Export the FINAL dateframe / Table ####
1. Export to CSV
- df.to_csv('final_table.csv', index=False)  # index=False to avoid writing row indices
2. Export to Excel
- df.to_excel('final_table.xlsx', index=False)  # Requires openpyxl or xlsxwriter installed
3. Export to JSON
- df.to_json('final_table.json', orient='records', lines=True)
4. Export to HTML
- df.to_html('final_table.html', index=False)

In [585]:
df.to_excel('Movie_Dataset_FINAL.xlsx', index=False)

## **Answering Business Questions** ##
1. What are the most common genres in the dataset, and how are they distributed?
2. Which movies have the highest and lowest ratings, and what are their common attributes (e.g., genre, runtime, stars)?
3. Which movies have the highest and lowest votes, and what are their common attributes (e.g., genre, runtime, stars)?
4. Who are the most influential directors and stars in terms of movie ratings and gross revenue?

### 1. What are the most common genres in the dataset? ###

**Steps:**
- **Observation:** I've noticed that the Genre Column contains multiple genres for one movie. It seems difficult to do calculation. Hence, I have to manipulate the Genre Column to answer the Business Question
- First, we split the Genre column into Lists
- Second, ensure that whitespace are clear from each genre string
- Third, Use the method **'explode'** whereby, it will help transform each list element into its own row

In [335]:
# Split the Genre column into Lists

In [576]:
df['GENRE'] = df['GENRE'].str.split(',')

In [336]:
# Strips any whitespace

In [327]:
df['GENRE'] = df['GENRE'].apply(lambda x: [genre.strip() for genre in x])

In [337]:
# Transform each list element into its own row for that one movie

In [343]:
exploded_genres = df.explode('GENRE')

In [340]:
# View of the 'exploded_genres' variable dataframe
# Each type of genre under one movie has its own row. This is for easier data manipulation.

In [577]:
exploded_genres

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
0,Blood Red Sky,2021,Action,6.1,"21,062",121.0,,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander ..."
0,Blood Red Sky,2021,Horror,6.1,"21,062",121.0,,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander ..."
0,Blood Red Sky,2021,Thriller,6.1,"21,062",121.0,,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander ..."
1,Masters of the Universe: Revelation,2021,Animation,5.0,"17,870",25.0,,,"Chris Wood, Sarah Michelle Gellar, Lena Head..."
1,Masters of the Universe: Revelation,2021,Action,5.0,"17,870",25.0,,,"Chris Wood, Sarah Michelle Gellar, Lena Head..."
...,...,...,...,...,...,...,...,...,...
9566,The Imperfects,2021,Drama,,,,,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna..."
9566,The Imperfects,2021,Fantasy,,,,,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna..."
9567,The Imperfects,2021,Adventure,,,,,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia..."
9567,The Imperfects,2021,Drama,,,,,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia..."
9567,The Imperfects,2021,Fantasy,,,,,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia..."

In [346]:
# Counts the total number of Genres within our Movie dataset and saved in a variable

In [365]:
total_genre_count = exploded_genres["GENRE"].value_counts()

In [578]:
total_genre_count

GENRE
Drama          4115
Comedy         2736
Action         2110
Adventure      1588
Animation      1584
Crime          1519
Documentary    1221
Thriller        895
Mystery         840
Romance         835
Fantasy         537
Horror          518
Family          442
Reality-TV      370
History         346
Biography       311
Sci-Fi          303
Short           247
Music           200
Sport           192
Game-Show        98
Talk-Show        89
                 78
Musical          61
War              48
Western          24
News             23
Film-Noir        12
Name: count, dtype: int64

In [372]:
# Finding out the maximum and minimum count and saves it in variable

In [368]:
max_count = total_genre_count.max()
max_count

4115

In [369]:
min_count = total_genre_count.min()
min_count

12

In [371]:
# Filter genres with the highest and lowest counts

In [375]:
highest_genre = total_genre_count[total_genre_count == max_count]

In [376]:
lowest_genre = total_genre_count[total_genre_count == min_count]

In [382]:
top_5_genres = total_genre_count.nlargest(5)

#### 1. What are the most common genres in the dataset? ####

Answer: 
1. The 5 most common or most popular genres in the dataset are as follows

In [384]:
print ("Top 5 Most popular Genres are:")
print(top_5_genres)

Top 5 Most popular Genres are:
GENRE
Drama        4115
Comedy       2736
Action       2110
Adventure    1588
Animation    1584
Name: count, dtype: int64

#### 1.1 What are the least common genres in the dataset? ####

Answer: 
1. The 5 least popular genres in the dataset are as follows

In [386]:
top_5_least_popular_genre = total_genre_count.nsmallest(5)

In [387]:
print ("Top 5 Least popular Genres are:")
print(top_5_least_popular_genre)

Top 5 Least popular Genres are:
GENRE
Film-Noir    12
News         23
Western      24
War          48
Musical      61
Name: count, dtype: int64

#### 1.2 What is the most popular genre in the dataset? ####

Answer: 
1. The most popular genre in the dataset is

In [379]:
print("Most popular Genre is:")
print(highest_genre)

Most popular Genre is:
GENRE
Drama    4115
Name: count, dtype: int64

#### 1.3 What is the least popular genre in the dataset? ####

Answer: 
1. The least popular genre in the dataset is

In [380]:
print("Least popular Genre is:")
print(lowest_genre)

Least popular Genre is:
GENRE
Film-Noir    12
Name: count, dtype: int64

#### Post Reflection ####

1. I realised that answering the Business Questions can affect our clean dataset. Hence, moving forward I will create copies for individual question to carry out the data manipulation to answer the question.

In [397]:
# Creating a copy of our clean dataset for data manipulation

In [398]:
movie_rating = df.copy()

In [407]:
# Reverting back to the clean dataset by filling NaNs with empty string

In [405]:
df["RATING"] = df["RATING"].fillna("")

### 2. Which movies have the highest and lowest ratings, and what are their common attributes (e.g., genre, runtime, stars)? ###

**Steps:**
- **Observation:** Some of the movies do not have ratings, hence, in this case we can remove or drop the rows with missing ratings
1. Convert the ratings column to numeric values
2. Drop the rows with missing ratings
3. Determine which movie has the highest and lowest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively
4. Determine which top 5 movies has the highest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively
5. Determine which top 5 movies has the lowest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively

In [390]:
# Converting the Rating column into numeric to see the empty strings turn into NaN

In [401]:
movie_rating["RATING"] = pd.to_numeric(movie_rating["RATING"], errors='coerce')

In [409]:
# Droping the rows that contains NaN under the 'Genre' column

In [410]:
movie_rating = movie_rating.dropna(subset=["RATING"])

In [412]:
# Check if any of the value in the RATING column is a null = False, means no null

In [411]:
movie_rating["RATING"].isnull().any()

False

#### 2.1 What is the highest and lowest rating movie in the dataset? ####

a) The highest rating movie in the dataset is

In [416]:
# Using .idxmax() this will show us which INDEX has the highest rating under the RATING column

In [418]:
highest_rating_index = movie_rating["RATING"].idxmax()
highest_rating_index

7578

In [424]:
# Using .loc[<Index no.>] will help to extract the movie row details

In [423]:
highest_rating_movie = movie_rating.loc[highest_rating_index]
highest_rating_movie

MOVIES                                        BoJack Horseman
YEAR                                                2014–2020
GENRE                              [Animation, Comedy, Drama]
RATING                                                    9.9
VOTES                                                  12,369
RunTime                                                  26.0
Gross
Director                                          Amy Winfrey
Stars       Will Arnett,  Amy Sedaris,  Alison Brie,  Paul...
Name: 7578, dtype: object

#### 2.1 What is the highest and lowest rating movie in the dataset? ####

b) The lowest rating movie in the dataset is

In [ ]:
# Using .idxmin() this will show us which INDEX has the lowest rating under the RATING column

In [429]:
lowest_rating_index = movie_rating["RATING"].idxmin()
lowest_rating_index

1166

In [424]:
# Using .loc[<Index no.>] will help to extract the movie row details

In [432]:
lowest_rating_movie = movie_rating.loc[lowest_rating_index]
lowest_rating_movie

MOVIES                                        Raketsonyeondan
YEAR                                                     2021
GENRE                                  [Comedy, Drama, Sport]
RATING                                                    1.1
VOTES                                                  25,629
RunTime                                                  80.0
Gross
Director
Stars       Kim Sang-kyung,  Na-ra Oh,  Tang Joon-sang,  S...
Name: 1166, dtype: object

#### 2.2 Top 5 movies has the highest rating movies in the dataset? ####

a) The Top 5 highest rating movies in the dataset are

- Re-arranmge the descending order
- Extract the top 5 movies with highest ratings

In [575]:
movie_rating_sorted_desc = movie_rating.sort_values(by="RATING", ascending=False)
movie_rating_sorted_desc

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
7578,BoJack Horseman,2014–2020,"[Animation, Comedy, Drama]",9.9,"12,369",26.0,,Amy Winfrey,"Will Arnett, Amy Sedaris, Alison Brie, Paul..."
8392,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.9,"8,813",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
9504,Dexter,2006–2013,"[Crime, Drama, Mystery]",9.8,"11,638",51.0,,Steve Shill,"Michael C. Hall, Julie Benz, Jennifer Carpen..."
8391,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.8,"5,283",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
8649,Dark,2017–2020,"[Crime, Drama, Mystery]",9.7,"20,230",73.0,,Baran bo Odar,"Sebastian Rudolph, Louis Hofmann, Dietrich H..."
...,...,...,...,...,...,...,...,...,...
5037,Hajwala,2016,"[Action, Adventure, Crime]",2.1,222,96.0,,"Ali Bin Matar, Ibrahim Bin Mohamed","Anwar Aljabri, Haleem Aljabri, Omar Aljabri,..."
3528,Sinister Squad,2016,"[Action, Comedy, Fantasy]",2.1,"1,025",90.0,,Jeremy M. Inman,"Johnny Rey Diaz, Christina Licciardi, Lindsa..."
4332,Way of the Vampire,2005,"[Action, Horror, Thriller]",2.0,"1,593",82.0,,"Sarah Nean Bruce, Eduardo Durão","Rhett Giles, Andreas Beckett, Paul Logan, D..."
5365,Defcon 2012,2010,[Sci-Fi],1.8,377,92.0,,R. Christian Anderson,"Shy Pilgreen, Dan Gruenberg, Brian Neil Hoff..."
1166,Raketsonyeondan,2021,"[Comedy, Drama, Sport]",1.1,"25,629",80.0,,,"Kim Sang-kyung, Na-ra Oh, Tang Joon-sang, S..."

In [444]:
top_5_highest_rating_movies = movie_rating_sorted_desc.head(5)
top_5_highest_rating_movies

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
7578,BoJack Horseman,2014–2020,"[Animation, Comedy, Drama]",9.9,"12,369",26.0,,Amy Winfrey,"Will Arnett, Amy Sedaris, Alison Brie, Paul..."
8392,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.9,"8,813",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
9504,Dexter,2006–2013,"[Crime, Drama, Mystery]",9.8,"11,638",51.0,,Steve Shill,"Michael C. Hall, Julie Benz, Jennifer Carpen..."
8391,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.8,"5,283",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
8649,Dark,2017–2020,"[Crime, Drama, Mystery]",9.7,"20,230",73.0,,Baran bo Odar,"Sebastian Rudolph, Louis Hofmann, Dietrich H..."

In [440]:
print("Top 5 movies with the highest ratings:")
print(top_5_highest_rating_movies)

Top 5 movies with the highest ratings:
                           MOVIES       YEAR                           GENRE  \
7578              BoJack Horseman  2014–2020      [Animation, Comedy, Drama]
8392   Avatar: The Last Airbender  2005–2008  [Animation, Action, Adventure]
9504                       Dexter  2006–2013         [Crime, Drama, Mystery]
8391   Avatar: The Last Airbender  2005–2008  [Animation, Action, Adventure]
8649                         Dark  2017–2020         [Crime, Drama, Mystery]

      RATING   VOTES RunTime Gross            Director  \
7578     9.9  12,369    26.0               Amy Winfrey
8392     9.9   8,813    92.0        Joaquim Dos Santos
9504     9.8  11,638    51.0               Steve Shill
8391     9.8   5,283    92.0        Joaquim Dos Santos
8649     9.7  20,230    73.0             Baran bo Odar

                                                  Stars
7578  Will Arnett,  Amy Sedaris,  Alison Brie,  Paul...
8392  Zach Tyler,  Mae Whitman,  Jack De Sena,  Mich...
9504  Michael C. Hall,  Julie Benz,  Jennifer Carpen...
8391  Zach Tyler,  Mae Whitman,  Jack De Sena,  Mich...
8649  Sebastian Rudolph,  Louis Hofmann,  Dietrich H...

#### 2.3 Top 5 movies has the lowest rating movies in the dataset? ####

a) The Top 5 lowest rating movies in the dataset are
- Re-arranmge the ascending order
- Extract the top 5 movies with lowest ratings

In [447]:
movie_rating_sorted_asc = movie_rating.sort_values(by="RATING", ascending=True)
movie_rating_sorted_asc

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
1166,Raketsonyeondan,2021,"[Comedy, Drama, Sport]",1.1,"25,629",80.0,,,"Kim Sang-kyung, Na-ra Oh, Tang Joon-sang, S..."
5365,Defcon 2012,2010,[Sci-Fi],1.8,377,92.0,,R. Christian Anderson,"Shy Pilgreen, Dan Gruenberg, Brian Neil Hoff..."
4332,Way of the Vampire,2005,"[Action, Horror, Thriller]",2.0,"1,593",82.0,,"Sarah Nean Bruce, Eduardo Durão","Rhett Giles, Andreas Beckett, Paul Logan, D..."
5037,Hajwala,2016,"[Action, Adventure, Crime]",2.1,222,96.0,,"Ali Bin Matar, Ibrahim Bin Mohamed","Anwar Aljabri, Haleem Aljabri, Omar Aljabri,..."
3528,Sinister Squad,2016,"[Action, Comedy, Fantasy]",2.1,"1,025",90.0,,Jeremy M. Inman,"Johnny Rey Diaz, Christina Licciardi, Lindsa..."
...,...,...,...,...,...,...,...,...,...
8519,She-Ra and the Princesses of Power,2018–2020,"[Animation, Action, Adventure]",9.7,"1,434",24.0,,"Christina Manrique, Roy Burdine","Aimee Carrero, Karen Fukuhara, AJ Michalka, ..."
9504,Dexter,2006–2013,"[Crime, Drama, Mystery]",9.8,"11,638",51.0,,Steve Shill,"Michael C. Hall, Julie Benz, Jennifer Carpen..."
8391,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.8,"5,283",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
8392,Avatar: The Last Airbender,2005–2008,"[Animation, Action, Adventure]",9.9,"8,813",92.0,,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
7578,BoJack Horseman,2014–2020,"[Animation, Comedy, Drama]",9.9,"12,369",26.0,,Amy Winfrey,"Will Arnett, Amy Sedaris, Alison Brie, Paul..."

In [450]:
top_5_lowest_rating_movies = movie_rating_sorted_asc.head(5)
top_5_lowest_rating_movies

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
1166,Raketsonyeondan,2021,"[Comedy, Drama, Sport]",1.1,"25,629",80.0,,,"Kim Sang-kyung, Na-ra Oh, Tang Joon-sang, S..."
5365,Defcon 2012,2010,[Sci-Fi],1.8,377,92.0,,R. Christian Anderson,"Shy Pilgreen, Dan Gruenberg, Brian Neil Hoff..."
4332,Way of the Vampire,2005,"[Action, Horror, Thriller]",2.0,"1,593",82.0,,"Sarah Nean Bruce, Eduardo Durão","Rhett Giles, Andreas Beckett, Paul Logan, D..."
5037,Hajwala,2016,"[Action, Adventure, Crime]",2.1,222,96.0,,"Ali Bin Matar, Ibrahim Bin Mohamed","Anwar Aljabri, Haleem Aljabri, Omar Aljabri,..."
3528,Sinister Squad,2016,"[Action, Comedy, Fantasy]",2.1,"1,025",90.0,,Jeremy M. Inman,"Johnny Rey Diaz, Christina Licciardi, Lindsa..."

In [451]:
print("Top 5 movies with the lowest ratings:")
print(top_5_lowest_rating_movies)

Top 5 movies with the lowest ratings:
                  MOVIES  YEAR                       GENRE  RATING   VOTES  \
1166     Raketsonyeondan  2021      [Comedy, Drama, Sport]     1.1  25,629
5365         Defcon 2012  2010                    [Sci-Fi]     1.8     377
4332  Way of the Vampire  2005  [Action, Horror, Thriller]     2.0   1,593
5037             Hajwala  2016  [Action, Adventure, Crime]     2.1     222
3528      Sinister Squad  2016   [Action, Comedy, Fantasy]     2.1   1,025

     RunTime Gross                             Director  \
1166    80.0
5365    92.0                      R. Christian Anderson
4332    82.0           Sarah Nean Bruce,  Eduardo Durão
5037    96.0        Ali Bin Matar,  Ibrahim Bin Mohamed
3528    90.0                            Jeremy M. Inman

                                                  Stars
1166  Kim Sang-kyung,  Na-ra Oh,  Tang Joon-sang,  S...
5365  Shy Pilgreen,  Dan Gruenberg,  Brian Neil Hoff...
4332  Rhett Giles,  Andreas Beckett,  Paul Logan,  D...
5037  Anwar Aljabri,  Haleem Aljabri,  Omar Aljabri,...
3528  Johnny Rey Diaz,  Christina Licciardi,  Lindsa...

In [ ]:
# Creating a copy of our clean dataset for data manipulation

In [453]:
movie_votes = df.copy()

### 3. Which movies have the highest and lowest votes, and what are their common attributes (e.g., genre, runtime, stars)? ###

**Steps:**
- Observation: Some of the movies do not have votes, hence, in this case we can remove or drop the rows with missing votes for easier data extraction of the highest and lowest voted movies.
1. Remove non-numeric characters from the VOTES column
2. Convert the Votes column to numeric values
3. 
Drop the rows with missing ratings

In [474]:
# Replacing the comma ',' between strings with empty strings - removing the comma

In [470]:
movie_votes["VOTES"] = movie_votes["VOTES"].str.replace(',','',regex=True)

In [477]:
# Converting the VOTES column into numeric - however, it may create floater (decimal places)

In [472]:
movie_votes["VOTES"] = pd.to_numeric(movie_votes["VOTES"], errors='coerce')

In [483]:
# Remove the rows with NaNs in the VOTES column

In [487]:
movie_votes = movie_votes.dropna(subset=["VOTES"])

In [498]:
# Convert the floater to Integer (whole number)
# May cause an error when working with a copy of the original dataset, hence, 
# to change floater to interger on a copy dataset - use '.loc[:, <COLUMN NAME>]'

In [491]:
movie_votes.loc[:, "VOTES"] = movie_votes["VOTES"].astype(int)

In [502]:
movie_votes_sorted_desc = movie_votes.sort_values(by='VOTES', ascending=False)
movie_votes_sorted_desc.head(5)

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
111,The Lord of the Rings: The Fellowship of the Ring,2001,"[Action, Adventure, Drama]",8.8,1713028,178.0,$315.54M,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, S..."
193,The Lord of the Rings: The Return of the King,2003,"[Action, Adventure, Drama]",8.9,1691777,201.0,$377.85M,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, ..."
16,Breaking Bad,2008–2013,"[Crime, Drama, Thriller]",9.4,1552311,49.0,,,"Bryan Cranston, Aaron Paul, Anna Gunn, Bets..."
260,The Lord of the Rings: The Two Towers,2002,"[Action, Adventure, Drama]",8.7,1529752,179.0,$342.55M,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, ..."
132,The Departed,2006,"[Crime, Drama, Thriller]",8.5,1227522,151.0,$132.38M,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholso..."

#### 3.1 Top 5 movies has the highest votes in the dataset? ####

a) The Top 5 highest voted movies in the dataset are
- Re-arranmge the descending order
- Extract the top 5 movies with highest votes

In [504]:
top_5_highest_votes_movies = movie_votes_sorted_desc.head(5)

In [505]:
print("Top 5 movies with the highest votes:")
print(top_5_highest_votes_movies)

Top 5 movies with the highest votes:
                                                MOVIES       YEAR  \
111  The Lord of the Rings: The Fellowship of the Ring       2001
193      The Lord of the Rings: The Return of the King       2003
16                                        Breaking Bad  2008–2013
260              The Lord of the Rings: The Two Towers       2002
132                                       The Departed       2006

                          GENRE RATING    VOTES RunTime     Gross  \
111  [Action, Adventure, Drama]    8.8  1713028   178.0  $315.54M
193  [Action, Adventure, Drama]    8.9  1691777   201.0  $377.85M
16     [Crime, Drama, Thriller]    9.4  1552311    49.0
260  [Action, Adventure, Drama]    8.7  1529752   179.0  $342.55M
132    [Crime, Drama, Thriller]    8.5  1227522   151.0  $132.38M

            Director                                              Stars
111    Peter Jackson  Elijah Wood,  Ian McKellen,  Orlando Bloom,  S...
193    Peter Jackson  Elijah Wood,  Viggo Mortensen,  Ian McKellen, ...
16                    Bryan Cranston,  Aaron Paul,  Anna Gunn,  Bets...
260    Peter Jackson  Elijah Wood,  Ian McKellen,  Viggo Mortensen, ...
132  Martin Scorsese  Leonardo DiCaprio,  Matt Damon,  Jack Nicholso...

#### 3.2 Top 5 movies has the lowest votes in the dataset? ####

a) The Top 5 lowest voted movies in the dataset are
- Re-arranmge the ascending order
- Extract the top 5 movies with lowest votes

In [503]:
movie_votes_sorted_asc = movie_votes.sort_values(by='VOTES', ascending=True)
movie_votes_sorted_asc.head(5)

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
8737,¡A cantar!,2020,"[Game-Show, Music]",7.2,5,38.0,,Salva Romero,"Ricky Merino, Barbara Orti"
8740,¡A cantar!,2020,"[Game-Show, Music]",7.2,5,39.0,,Salva Romero,Ricky Merino
9168,3Below: Tales of Arcadia,2018–2019,"[Animation, Action, Adventure]",7.6,5,1.0,,,
6967,La Reina de Indias y el Conquistador,2020,"[Drama, History]",6.8,5,,,,"Emmanuel Esparza, Essined Aponte, Manuel Nav..."
8546,Meerkat Manor,2005–2008,[Documentary],9.2,5,23.0,,Star: Stockard Channing,

In [506]:
top_5_lowest_votes_movies = movie_votes_sorted_asc.head(5)

In [508]:
print("Top 5 movies with the lowest votes:")
print(top_5_lowest_votes_movies)

Top 5 movies with the lowest votes:
                                     MOVIES       YEAR  \
8737                             ¡A cantar!       2020
8740                             ¡A cantar!       2020
9168               3Below: Tales of Arcadia  2018–2019
6967   La Reina de Indias y el Conquistador       2020
8546                          Meerkat Manor  2005–2008

                               GENRE RATING  VOTES RunTime Gross  \
8737              [Game-Show, Music]    7.2      5    38.0
8740              [Game-Show, Music]    7.2      5    39.0
9168  [Animation, Action, Adventure]    7.6      5     1.0
6967                [Drama, History]    6.8      5
8546                   [Documentary]    9.2      5    23.0

                     Director  \
8737             Salva Romero
8740             Salva Romero
9168
6967
8546  Star: Stockard Channing

                                                  Stars
8737                        Ricky Merino,  Barbara Orti
8740                                       Ricky Merino
9168
6967  Emmanuel Esparza,  Essined Aponte,  Manuel Nav...
8546

### 4. Who are the most influential directors and stars in terms of movie ratings and gross revenue? ###

**Steps:**
- **Observation:** Some of the movies do not have ratings, hence, in this case we can remove or drop the rows with missing ratings
1. Convert the ratings column to numeric values
2. Drop the rows with missing ratings
3. Determine which movie has the highest and lowest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively
4. Determine which top 5 movies has the highest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively
5. Determine which top 5 movies has the lowest ratings with the following attributes (Genre, RunTime, Stars, Votes) respectively

#### 4.1 Who are the most influential directors based on the movie ratings? ####

a) The Top 5 most influential directors with the highest voted movies in the dataset are
- Based on the top 5 highest rated movies from question 3, we can see the top directors and stars:

In [562]:
top_5_highest_rating_movies[["MOVIES","RATING","Director", "Stars"]]

,MOVIES,RATING,Director,Stars
7578,BoJack Horseman,9.9,Amy Winfrey,"Will Arnett, Amy Sedaris, Alison Brie, Paul..."
8392,Avatar: The Last Airbender,9.9,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
9504,Dexter,9.8,Steve Shill,"Michael C. Hall, Julie Benz, Jennifer Carpen..."
8391,Avatar: The Last Airbender,9.8,Joaquim Dos Santos,"Zach Tyler, Mae Whitman, Jack De Sena, Mich..."
8649,Dark,9.7,Baran bo Odar,"Sebastian Rudolph, Louis Hofmann, Dietrich H..."

#### 4.2 Who are the most influential directors and stars based on the movie gross revenue? ####

a) The Top 5 most influential directors with the highest gross revenue for movies in the dataset are:

- **Observation:** During data cleaning we replaced NaN under Gross column as an empty string to standardised the dataset. However, now upon answer the business question, we have to revert back to NaN to properly handle missing values.

1. Make a copy from the original cleaned dataset
2. Replace the empty string (orig: NaN) back to NaN for easier handling of missing values
3. Drop the NaN rows under Gross column
4. Filter descending / ascending order of Gross column to find out the top 5 highest grossing movies
5. Extract out the Directors and Stars respectively

In [518]:
# Creating a copy of the original dataframe for data manipulation

In [541]:
movie_gross = df.copy()

In [515]:
# Checking the type of the 'Gross' column - Object (typically used for strings)

In [544]:
movie_gross["Gross"].dtypes

dtype('O')

In [555]:
# Replaces the empty string to NaN (reverting back to the initial state)

In [552]:
movie_gross['Gross'] = movie_gross['Gross'].replace('', np.nan)

In [554]:
# Shows the NOT NULL Gross column values

In [553]:
movie_gross[movie_gross["Gross"].notnull()]

,MOVIES,YEAR,GENRE,RATING,VOTES,RunTime,Gross,Director,Stars
77,The Hitman's Bodyguard,2017,"[Action, Comedy, Crime]",6.9,"205,979",118.0,$75.47M,Patrick Hughes,"Ryan Reynolds, Samuel L. Jackson, Gary Oldma..."
85,Jurassic Park,1993,"[Action, Adventure, Sci-Fi]",8.1,"897,444",127.0,$402.45M,Steven Spielberg,"Sam Neill, Laura Dern, Jeff Goldblum, Richa..."
95,Don't Breathe,2016,"[Crime, Horror, Thriller]",7.1,"237,601",88.0,$89.22M,Fede Alvarez,"Stephen Lang, Jane Levy, Dylan Minnette, Da..."
111,The Lord of the Rings: The Fellowship of the Ring,2001,"[Action, Adventure, Drama]",8.8,"1,713,028",178.0,$315.54M,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, S..."
125,Escape Room,I) (2019,"[Action, Adventure, Horror]",6.4,"99,351",99.0,$57.01M,Adam Robitel,"Taylor Russell, Logan Miller, Jay Ellis, Ty..."
...,...,...,...,...,...,...,...,...,...
5750,Vidal Sassoon: The Movie,2010,[Documentary],6.5,245,90.0,$0.09M,Craig Teper,"Beverly Adams, Elgin Charles, Grace Coddingt..."
5770,Men at Lunch,2012,"[Documentary, Mystery]",6.3,331,75.0,$0.00M,Seán Ó Cualáin,"Fionnula Flanagan, Peter Quinn, Ric Burns, ..."
5835,Decoding Deepak,2012,[Documentary],5.5,124,83.0,$0.01M,Gotham Chopra,"Deepak Chopra, Gotham Chopra"
6056,Theo Who Lived,2016,[Documentary],6.8,111,86.0,$0.01M,David Schisgall,Theo Padnos
6292,Southern Justice,2006,"[Action, Adventure, Thriller]",3.1,126,96.0,$0.14M,M.D. Selig,"M.D. Selig, Michael Childers, Lisa Robert, ..."

In [558]:
# Dropping the NaN rows from the Gross column

In [557]:
movie_gross = movie_gross.dropna(subset=["Gross"])

#### 4.2.1 Top 5 most influential directors with the highest gross movies ####

a) The Top 5 most influential directors with the highest gross movies in the dataset are
- Based on the top 5 highest gross movies from question 3, we can see the top directors and stars:

In [564]:
movie_gross_sorted_desc = movie_gross.sort_values(by='Gross', ascending=False)
movie_gross_sorted_desc[["MOVIES","Gross","Director","Stars"]].head(5)

,MOVIES,Gross,Director,Stars
421,Sausage Party,$97.69M,"Greg Tiernan, Conrad Vernon","Seth Rogen, Kristen Wiig, Jonah Hill, Alist..."
582,Public Enemies,$97.10M,Michael Mann,"Christian Bale, Johnny Depp, Christian Stolt..."
262,Legally Blonde,$96.52M,Robert Luketic,"Reese Witherspoon, Luke Wilson, Selma Blair,..."
383,Dead Poets Society,$95.86M,Peter Weir,"Robin Williams, Robert Sean Leonard, Ethan H..."
793,Flashdance,$94.90M,Adrian Lyne,"Jennifer Beals, Michael Nouri, Lilia Skala, ..."

#### 4.2.2 Top 5 least influential directors with the lowest gross movies ####

a) The Top 5 least influential directors with the lowest gross movies in the dataset are

In [563]:
movie_gross_sorted_asc = movie_gross.sort_values(by='Gross', ascending=True)
movie_gross_sorted_asc[["MOVIES","Gross","Director","Stars"]].head(5)

,MOVIES,Gross,Director,Stars
1111,I Spit on Your Grave 2,$0.00M,Steven R. Monroe,"Jemma Dallender, Joe Absolom, Yavor Baharov,..."
4637,Life's a Breeze,$0.00M,Lance Daly,"Kelly Thornton, Fionnula Flanagan, Pat Short..."
4641,The Reconstruction of William Zero,$0.00M,Dan Bush,"Conal Byrne, Amy Seimetz, Scott Poythress, ..."
4648,Dayveon,$0.00M,Amman Abbasi,"Devin Blackmon, Dontrell Bright, Lachion Buc..."
4783,Green is Gold,$0.00M,Ryon Baxter,"Derek W. Adam, Jimmy Baxter, Ryon Baxter, B..."